### ISSUE TITLE
Can't use plugin with Jest

### ISSUE THREAD

**Issue by cliffhall** [GoogleChromeLabs/babel-plugin-transform-jsbi-to-bigint#3]
```
npm install jsbi babel-plugin-transform-jsbi-to-bigint --save
+ jsbi@3.0.0
+ babel-plugin-transform-jsbi-to-bigint@1.1.0
added 2 packages in 45.94s
```

In MyJSBITest.js

```js
import JSBI from 'jsbi/dist/jsbi.mjs'; // Only way to actually reach...

describe('A JS script', () => {
  it('can use JSBI', () => {
    const multiplier = JSBI.BigInt('256');
    expect( multiplier ).not.toBeUndefined();
  });
});
```
Running test
```
> npx jest

 FAIL  src/test/MyJSBITest.js
  ● Test suite failed to run

    SyntaxError: /Users/.../src/test/MyJSBITest.js: NodePath has been removed so is read-only. (This is an error on an internal node. Probably an internal error)

      at File.buildCodeFrameError (node_modules/babel-core/lib/transformation/file/index.js:427:15)
      at NodePath.buildCodeFrameError (node_modules/babel-traverse/lib/path/index.js:140:26)
      at NodePath._assertUnremoved (node_modules/babel-traverse/lib/path/removal.js:70:16)
      at NodePath.remove (node_modules/babel-traverse/lib/path/removal.js:20:8)
      at PluginPass.exit (node_modules/babel-plugin-transform-jsbi-to-bigint/dist/index.js:130:20)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:117:8)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)

Test Suites: 1 failed, 0 passed, 1 total

```

**Comment by jakobkummerow** [comment]
Note on your test: you want `JSBI.BigInt('256')` rather than `new JSBI('256')`.

@mathiasbynens : Looks like the import statement replacement needs to be a bit more generic. Maybe changing it from `/jsbi/i` to `/.*\/jsbi/i` would do the trick?

**Comment by cliffhall** [comment]
Doh! Thanks @jakobkummerow. I'll just go stand in the corner with this dunce hat on now...

**Comment by cliffhall** [comment]
Belay that retraction. It works in the browser, but in Jest, still has a problems, just a different one:

With everything the same as above except:

```
    it( "can use JSBI", () => {
        const multiplier = JSBI.BigInt('256');
        expect( multiplier ).not.toBeUndefined();
   });
```

Running Jest
```
> npx jest

 FAIL  src/test/MyJSBITest.js
  ● Test suite failed to run

    TypeError: /Users/.../src/test/MyJSBITest.js: t.bigIntLiteral is not a function

      at createBigIntConstructor (node_modules/babel-plugin-transform-jsbi-to-bigint/dist/index.js:75:16)
      at createExpression (node_modules/babel-plugin-transform-jsbi-to-bigint/dist/index.js:32:14)
      at PluginPass.CallExpression (node_modules/babel-plugin-transform-jsbi-to-bigint/dist/index.js:197:28)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitSingle (node_modules/babel-traverse/lib/context.js:108:19)
      at TraversalContext.visit (node_modules/babel-traverse/lib/context.js:192:19)

Test Suites: 1 failed, 0 passed, 1 total
```

Doesn't matter if pass in a string or a number, I get the same error.

**Comment by mathiasbynens** [comment]
### `package.json`

```json
{
  "private": true,
  "dependencies": {
    "babel-plugin-transform-jsbi-to-bigint": "^1.1.0",
    "jsbi": "^3.0.1"
  }
}
```

### `test.js`

```js
import JSBI from './node_modules/jsbi/dist/jsbi.mjs'; // Only way to actually reach...

describe('A JS script', () => {
  it('can use JSBI', () => {
    const multiplier = JSBI.BigInt('256');
    expect(multiplier).not.toBeUndefined();
  });
});
```

### Version numbers

```
$ node -v
v12.6.0

$ npx jest -v
npx: installed 479 in 17.815s
24.8.0
```

### Results

**Disclaimer:** I'm not familiar with `jest`.

```
$ npx jest
npx: installed 479 in 16.538s
 FAIL  ./test.js
  ● Test suite failed to run

    /tmp/ajsdiosajdoiasjdioas/test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import JSBI from './node_modules/jsbi/dist/jsbi.mjs'; // Only way to actually reach...
                                                                                                    ^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (~/.npm/_npx/29376/lib/node_modules/jest/node_modules/@jest/transform/build/ScriptTransformer.js:471:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.009s
Ran all test suites.
```

This makes sense, given that Node.js doesn't yet support modules by default --- unless `jest` is supposed to transpile static `import`, in which case, please file a jest bug.

For now, why not use the CommonJS version?

```js
const JSBI = require('./node_modules/jsbi/dist/jsbi-cjs.js');

describe('A JS script', () => {
  it('can use JSBI', () => {
    const multiplier = JSBI.BigInt('256');
    expect(multiplier).not.toBeUndefined();
  });
});
```

This works for me:

```
$ npx jest
npx: installed 479 in 17.657s
 PASS  ./test.js
  A JS script
    ✓ can use JSBI (3ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.089s
Ran all test suites.
```

**Comment by cliffhall** [comment]
@mathiasbynens this is a workaround not a fix. The test I presented above is a small-world example made specifically to point out the problem with no extraneous fluff to consider.

Your workaround is *not* acceptable in my actual situation, where the import is done in a javascript domain entity class which is actually the code under test. That class is used in a React application. Babel is configured to allow imports in Jest. 

**.babelrc**
```
{
  "plugins": ["transform-jsbi-to-bigint"],
  "presets": [[ "env", { "modules": "commonjs" } ]],
    "env": {
      "test": {
        "presets": [
          [
            "env",
            {
              "targets": {
                "node": "current"
              }
            }
          ]
        ]
      }
    }
  }
```

All of my other entities that use imports test fine. But the first operation that is used in an entity that imports JSBI gives the following error

```
 TypeError: /Users/.../src/test/MyEntityTest.js: t.bigIntLiteral is not a function
```

So, should I open another issue and copy all this into it, or will you reopen this one and consider why ```t.bigIntLiteral is not a function``` if the JSBI class has been imported?

**Comment by mathiasbynens** [comment]
It would be helpful to provide a minimal repro gist/repo that allows me to reproduce the exact issue you're having. My previous comment includes the output I was seeing which differs from what you're reporting.

**Comment by mathiasbynens** [comment]
"`t.bigIntLiteral` is not a function" seems to indicate you're using an older version of Babel somehow?

**Comment by cliffhall** [comment]
@mathiasbynens I just checked my versions of node and jest against yours and discovered that I was a major rev behind on jest (23 v 24).  I installed 24 and now it's all peachy. Thanks much for your help.

**Comment by cliffhall** [comment]
BTW, I'm suggesting to the web3.js team that they use JSBI to get ahead of the game. They dropped Bignumber.js, went to BN.js, found issues and are thinking of reverting back to Bignumber.js. IMHO, JSBI is the right way to go when considering a big number solution at this point in time, because it will soon reflect native JS. Thanks for the Chrome Labs team for making this plugin available so we can all adopt JSBI and begin preparation for widespread implementation of BigInt.
